### ISSUE TITLE
Seems to run too early on lastest OpenWRT/LEDE

### ISSUE THREAD

**Issue by ilmaisin** [cvmiller/v6brouter#11]
I am running LEDE Reboot `(17.01.4, r3560-79f57e422d)`. The "OpenWRT" version of script works, except when I put it on the startup, it seems to run too early and the clients won't get IPv6 addresses. I inserted the line `sleep 5` to the beginning of the script and it seems to work around the issue.

**Comment by cvmiller** [comment]
I'll update the Doc to suggest putting in a 5 second wait when using the script at startup time.

**Comment by cvmiller** [comment]
Added the following to the Doc:

> Note: Due to the timing of when interfaces actually become available, you may have to add a sleep 5; before the script if you find that v6brouter is not working as expected on reboot.

Closing.
