### ISSUE TITLE
Is it possible to assign REAL IPv6 address under broute mode?

### ISSUE THREAD

**Issue by kotori2** [cvmiller/v6brouter#13]
Such as create an interface and add it to br-lan?

**Comment by cvmiller** [comment]
Not sure what you mean by "real" IPv6 address. In Broute mode, the IPv6 address is just used for management of the router via IPv6 (it can still be reached via IPv4 as well). The Globally Unique (GUA) IPv6 address should be something chosen from your ISPs /64. By entering that address in the script variable BRIDGE_IP6, the script will assign that IPv6 address to the br-lan device.

**Comment by kotori2** [comment]
Thanks for replying. If I assign a valid GUA address, can I reach router
from WAN? Or should I assign that address to WAN rather than br-lan?

Craig Miller <notifications@github.com> 于 2018年11月4日周日 02:15写道：

**Comment by cvmiller** [comment]
If you want to access it via the WAN, then you will need to either A) don't run the firewall (not recommended), or B)set up an ip6tables firewall rule to allow access. 

There is an example in the script which does exactly this (allow WAN access with the firewall enabled) for SSH in the script.

**Comment by kotori2** [comment]
Thank you. It works magically lol
