### ISSUE TITLE
sysctl: error: 'net.bridge.bridge-nf-call-ip6tables' is an unknown key

### ISSUE THREAD

**Issue by garikaib** [cvmiller/v6brouter#15]
Just wanted to say thank you for creating this awesome script. Now my IPv6 Lan is working. However, when I run the script with the -F option I get an error.
`./v6brouter_openwrt.sh -E -F
--- checking for ebtables
/usr/sbin/ebtables
--- configuring v6 bridge
brctl: bridge br-lan: Resource busy
bridge name	bridge id		STP enabled	interfaces
br-lan		7fff.b04e266d35a8	no		eth0.1
							wlan0
							eth0.2
Bridge table: filter

Bridge chain: INPUT, entries: 0, policy: ACCEPT

Bridge chain: FORWARD, entries: 1, policy: ACCEPT
-p IPv6 -i eth0.2 -j mark --mark-set 0x10 --mark-target CONTINUE

Bridge chain: OUTPUT, entries: 0, policy: ACCEPT
--- Disable IPv6 RA and DHCPv6 Server on LAN
--- assigning IPv6 management address 2001:470:ebbd:0::11 to br-lan
--- configuring brouter to route everything but IPv6
Bridge table: broute

Bridge chain: BROUTING, entries: 1, policy: ACCEPT
-p ! IPv6 -i eth0.2 -j DROP 
--- Allow ports from user rules (from eth0.2) via ip6tables, block all others
Chain forwarding_rule (1 references)
target     prot opt source               destination         
ACCEPT     all      anywhere             anywhere             mark match 0x10 ctstate RELATED,ESTABLISHED
ACCEPT     all      anywhere             anywhere             mark match 0x10 ctstate RELATED,ESTABLISHED
ACCEPT     ipv6-icmp    anywhere             anywhere             mark match 0x10
DROP       all      anywhere             anywhere             mark match 0x10
ACCEPT     ipv6-icmp    anywhere             anywhere             mark match 0x10
DROP       all      anywhere             anywhere             mark match 0x10
--- enable ip6tables firewall for v6Bridge
sysctl: **error: 'net.bridge.bridge-nf-call-ip6tables' is an unknown key
`**

**Comment by cvmiller** [comment]
Could you provide a little more info about the machine you are using the v6brouter.sh script on (e.g. type of router, version of OpenWrt, etc).

**Comment by garikaib** [comment]
I am using a TP-Link MR3420 V5, OpenWrt 18.06.2, r7676-cddd7b4c77, ash shell on BusyBox v1.28.4. The only changes I made on it was installing your brouter script's dependencies i.e. ip and ebtables.

**Comment by cvmiller** [comment]
OK, thanks. Let me re-setup the environment, and see what is going on.

**Comment by cvmiller** [comment]
Please try version 2.0.3. 

It would appear that the bridge kernel module no longer implements this "key". 

I have also updated automatic WAN_DEV detection in the v6brouter.conf file. Yours won't need to change, but on future routers, it will make it easier to configure.

**Comment by garikaib** [comment]
Now working perfectly thank you.

**Comment by cvmiller** [comment]
Great to hear.
