### ISSUE TITLE
Not working on OpenWrt 22.03.3

### ISSUE THREAD

**Issue by andrea1388** [cvmiller/v6brouter#19]
Package ip is no more available and iptables isn't installed.
Any idea?
Regards, Andrea

opkg install ip
Unknown package 'ip'.

iptables: not found

**Comment by cvmiller** [comment]
I need to update the document. As of Openwrt 22.03, it has changed to using NetFilter (NFT). Therefore you will need to install the "nft" versions of ebtables and ip (if it isn't already installed, which it should be).

```
opkg update
opkg install ebtables-nft 
opkg install ip6tables-nft
opkg install iptables-nft
opkg install ip-full
```

**Comment by cvmiller** [comment]
Updated the document for NFT installation. Closing.
