### ISSUE TITLE
ip: not found in CC 15.05.1

### ISSUE THREAD

**Issue by lirundong** [cvmiller/v6brouter#2]
It's so strange that 15.05.1 doesn't have `ip` command, so this scripts doesn't work at my WNDR3800

``` bash
root@OpenWrt:~# ip
-ash: ip: not found
```

want to know which package include `ip` T_T

**Comment by cvmiller** [comment]
I agree, it is odd.

The package you want is 'ip' or 'ip-full'. Either will work.

I'll update the documentation to include 'ip' as a dependency.

thanks,

Craig...

## 

IPv6 is the future!
http://ipv6-net.blogspot.ca/

**Comment by cvmiller** [comment]
Updated documentation. Closing.
