### ISSUE TITLE
OpenWRT supports --arp-ip-dst

### ISSUE THREAD

**Issue by Carnildo** [cvmiller/v6brouter#3]
If you install the `kmod-ebtables-ipv4` package, the necessary kernel modules for ` --arp-ip-dst` are installed.  This permits the router to be configured to respond to ARP requests, which is rather useful if your router does more than just routing.

**Comment by cvmiller** [comment]
A good point. Let me test that in the script.

**Comment by cvmiller** [comment]
Incorporated into script. Will use kmod if available.
