### ISSUE TITLE
errors on my end.

### ISSUE THREAD

**Issue by HikeAndMap** [cvmiller/v6brouter#4]
ip: RTNETLINK answers: File exists

-1) after committing the script I lose my ipv4 internet.
-2) ipv6 dns server won't set on the clients behind the wrt router

-R argument fixes it back to original (or reboot)

**Comment by cvmiller** [comment]
1) Please fun script with as:
sh -x ./v6brouter_openwrt.sh, and attach output to this issue.
2) Depending on your client, you may or may not get IPv6 DNS. Linux, Android 5+ should get DNS from the RA (Router Advertisement) if the ISP is sending RDNSS in the RA. Windows requires a DHCPv6 server to obtain a DNS server. If your ISP is not supporting DHCPv6, then the Windows clients will not get IPv6 DNS server info.

**Comment by cvmiller** [comment]
Please try again with Version 2.0.d. It is a rewite, and no longer makes changes to the IPv4 networking, which should prevent the behaviour you saw.

**Comment by HikeAndMap** [comment]
Hi Craig,
 
thank you for the updates!
Saw your mail earlier but no time: work, 4 kids, sick wife..
 
I’m not sure if I can test it this evening as I’m still stuck in work,
but my first break tomorrow I’ll give it a go with the updated
version.
 
Have a nice evening
 
Vincent

**Comment by HikeAndMap** [comment]
Hi Graig,

finally found some time to test the new script.
4 kids, work (self-employed) , parents in law visiting whole more week.

Thank you for your work! First impression is:"very good!"

The new script of yours seem to work. At least improvements are quite obvious.
There's still an issue though.

All IPv6 websites work, first of all! I think that's the most important!
IPv4 seems to work as well, not loosing the connection anymore after a while (but I keep the computer running all night to be sure)

http://test-ipv6.com/ says everything green and working
however:
http://ipv6-test.com/

Score 
 
 
 
 18 / 20 
 
 
How can you improve your score ? 


1. Reconfigure your firewall

Your  router or firewall is filtering ICMPv6 messages sent to your computer.  An IPv6 host that cannot receive ICMP messages may encounter problems  like some web pages loading partially or not at all.


ICMP             
	Filtered 	

This is most likely because of the bridging as it's not a standard method thus the firewall needs to be adapted I assume. Would you know what I'd need to do to get here a 20/20 so I have indeed
fully native bridged IPv6 and disable the firewall on Ipv6 completely? I mean, the ISP router already has a firewall on IPv6 and every single port blocked. So I'm sure I can disable the firewall
on LEDE/OpenWRT

except, when the ISP Firewall supports UPnP of course. UPnP allows everyone on the planet of course to send a backdoor/trojan/etc and open the port from within. So maybe then firewall on
openWRT/LEDE is actually a good thing. But in that case, how can I be sure all ports are blocked? 

or.. shoudl ICMP never be blocked at all?


Hope you know the answers to these questions and I'm not too annoying asking so much.


thank you once again.

Yours sincerely,

Vincent Veldman

**Comment by cvmiller** [comment]
Hi Vincent,

ICMP for IPv6 is different from IPv4. But there are still ICMP Type numbers which are OK to filter. You can find out more info at:
http://ipv6-net.blogspot.com/2015/11/ipv6-using-icmp6.html

As for the firewall, if your upstream router is doing firewalling, a good test is to disable the firewall on v6brouter (by not using the '-F' optoin when starting up v6brouter). The bridging firewall in v6brouter allows _all_ ICMPv6 through, so I would be surprised if it improves your test-ipv6 score. But it is worth a try to disable the firewall on the v6brouter to see if it improves your test-ipv6 score.

Craig...

**Comment by cvmiller** [comment]
Is this still an issue for you with the firewall disabled?

**Comment by HikeAndMap** [comment]
Hi Craig,
 
yes with firewall enabled/disabled I get 18/20 score
 
Although all IPv6 websites are working 100% so it seems, but when
I put a non-Openwrt/lede from asus to my internet connection which supports IPv6
I get 20/20 score.
 
With the Lede (but same for openWRT) and your script I do get this message
score 18/20 and that ICMP is Filtered.
 
I don’t understand why, because it’s just bridging only the IPv6 right?
And in bridging you’d expect all ICMP getting through.
 
But although that particular website gives me a score of 18/20 like come ICMP
would not getting through, all websites do function properly.
 
So, most likely ICMP which aren’t important for normal internet usage.
 
It’s a pity the website doesn’t specify which ICMP we’re talking about.

**Comment by cvmiller** [comment]
Interesting, thank you for the feedback. If you are using the latest (v 2.01), you will note that there is a firewall rule to pass all ICMPv6. While it is true that v6brouter is bridging IPv6, with the firewall enabled, packets are sent up to ip6filters where they are blocked from the WAN interface, if: 1) they are not SSH, 2) they are not ICMPv6, 3) they are not a response from an earlier LAN request (using conntrack). 

If you look at the firewall settings in the LuCI GUI, you will see that there are rate limits on ICMPv6. This may be what ipv6-test.com is actually complaining about. And it is not a bad idea to have those rate limits in place.

I am glad to hear that you can surf the IPv6 internet even with the v6brouter firewall enabled.

Can we close this issue?

**Comment by HikeAndMap** [comment]
Yes, can be closed. I’ll reopen or open a new if I find anything not working.
 
right now everything is working.

**Comment by cvmiller** [comment]
Thanks, good to hear everything is working. Closing.
