### ISSUE TITLE
WIRELESS=$(brctl show | grep 'wlan')

### ISSUE THREAD

**Issue by HikeAndMap** [cvmiller/v6brouter#5]
# determine wireless interfaces in use
WIRELESS=$(brctl show | grep 'wlan')

exactly what does it do? I don't see any usage for it.

**Comment by cvmiller** [comment]
This is a stub. The script needs to be enhanced to take into account that not all wireless interfaces share the same MAC address as the "LAN".

**Comment by cvmiller** [comment]
I have reworked the script, and now longer need these lines. They have been removed in version 2.0.d of the script.

Closing this issue.
