### ISSUE TITLE
Could this work if the uplink is over wireless in client mode?

### ISSUE THREAD

**Issue by tvogel** [cvmiller/v6brouter#8]
I just tried this with my setup where previously, I had an IPv4 NATed "routed repeater" with the uplink being wlan0 in client mode and a different WLAN in AP mode on wlan0-1. I set WAN_DEV to "wlan0" but `./v6brouter_openwrt.sh -E` tells me

`brctl: bridge br-lan: Operation not supported`

Might be related to this http://serverfault.com/questions/152363/bridging-wlan0-to-eth0 . Do you have a hint how I could get this working?

**Comment by cvmiller** [comment]
Thanks for thinking of v6brouter, but your topology is not supported. There are real problems beyond v6brouter for getting IPv6 across a WLAN link in client mode. As best as I have seen, it doesn't work. 

If you think this is in error, or that you have it working, please send the output of 'ifconfig' to confirm that your WLAN client address has an IPv6 address.

**Comment by cvmiller** [comment]
Closing this issue.
