### ISSUE TITLE
How to set up IPV6 brouter for PPPOE

### ISSUE THREAD

**Issue by turkey-1** [cvmiller/v6brouter#9]
Hi, cvmiller,

Your project is awesome! My ISP provides both IPV4 and IPV6, but I have to dial pppoe to get the both internet access. I tried to brouter the IPV6, but I cannot figure out how. Is there a method? Thank you!

**Comment by turkey-1** [comment]
Right now I am using the NAT6 to give subnet IPV6 access.

**Comment by cvmiller** [comment]
Unfortunatley, PPPoE interface is not supported by bridging (which is what v6brouter uses). If you had a ISP box that would un-encapsulate the PPPoE first, and provide just ethernet, then v6brouter would work (bridging ethernet to ethernet).

Is there an option to use DHCPv6-PD (Prefix Delegation) on your router? That would be the "better" way of getting a prefix to use on your LAN. Unfortunately NAT6 although it works, does nothing to get ride of NAT, which makes networking devilishly difficult (just try to track/debug a user's use through NAT to understand what I am talking about).

**Comment by turkey-1** [comment]
Right now I am using the NAT6. The ISP does not provide a modem, there is one cable, so that I think I will continue with NAT6. Thank you!

**Comment by cvmiller** [comment]
Best of luck, hopefully you can get rid of the NAT6 soon.
